spring:
  application:
    name: mall-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/susan_mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

server:
  port: 8011

#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG
